### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by sebastian-schindler** [RRZE-Webteam/rrze-legal#102]
The following translation into English is wrong.

```
    {{imprint_websites_extra}}
    Dieses Impressum gilt nur für die Webauftritte unter den Adressen:<br>
    {{:imprint_websites_extra}}
    Dieses Impressum gilt nur für den Webauftritt unter dieser Adresse.<br>
    {{/imprint_websites_extra}}
```

The German text in the second version of the sentence does not end with a colon, while the English version does end with a colon, suggesting a list of websites to follow (which is not foreseen):

```
    {{imprint_websites_extra}}
    This imprint only belongs to the following websites:<br>
    {{:imprint_websites_extra}}
    This imprint only belongs to the following website:<br>
    {{/imprint_websites_extra}}
```

**Comment by rvdforst** [comment]
Ist erledigt! Vgl: https://github.com/RRZE-Webteam/rrze-legal/commit/1ff1c60aea7114d85844e1a3fbaf4abf23b04176
