### ISSUE TITLE
Dashboard-Meldung bei nicht vollständigen Daten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-legal#16]
Wenn die rechtlich relevanten Daten nicht eingegeben wurden, soll eine deutlich sichtbare Warnmeldung auf dem Dashboard erscheinen.
Vergleichbar mit dieser Meldung, die auf dem Impressum erscheint, wenn der Webmaster die Daten des Impressums nicht eintrug:

![grafik](https://user-images.githubusercontent.com/1070669/155538773-770a9e9c-f8b5-47d9-ac1b-952fed6094e7.png)

**Comment by rvdforst** [comment]
erledigt
