### ISSUE TITLE
Fehlerhafte Verwendung von ARIA-Attributen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-legal#19]
Im Footer auf Beta für den Consent-Banner:

```
<a ... aria-label="Datenschutzerklärung" ...>Datenschutzerklärung</a>
```

Was soll dieses aria-label denn machen? So ist die Nutzung falsch und eher eine Barriere, weil der Text dann doppelt vorgelesen wird.

**Comment by rvdforst** [comment]
erledigt
