### ISSUE TITLE
Oemebeds für Twitter

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-legal#42]
auf dieser Seite wurde auch Twitter eingebunden: https://www.beta.wordpress.rrze.fau.de/tests/standard-oembeds/
Dafür fehlt aber die Zustimmungsbox auf der Seite, im Impressum und im Constenbanner.
Wie können wir gewährlisten, dass Beiträge aus SM, wenn sie denn eingefügt werden auf der Webseite automatisch auch im Consentbanner mit aufgeführt werden?

**Comment by xwolfde** [comment]
ist umgesetzt
