### ISSUE TITLE
Ergänzung um eingesetzte Software / Clouddienste

### ISSUE THREAD

**Issue by uni-it-law** [RRZE-Webteam/rrze-legal#63]
[Auch im Rahmen von Software und Clouddiensten werden personenbezogene Daten verarbeitet.]

Idee der Informationen zu den Softwareanbeitern

## Auswertung von Nutzungsdaten durch der Verantwortlichen
 Ja/ Ja in Pseudonymisierter Form / Ja in anonymisierter Form / Nein
## Auswertung von Nutzungsdaten durch den Anbieter
 Ja/ Ja in Pseudonymisierter Form / Ja in anonymisierter Form / Nein
## Beteiligung von Telekommunikationsdienstleistern auf Seiten des Anbieters
 Ja/Nein
## Beteiligung von Unterauftragsverarbeitern auf Seiten des Anbieters
 Ja/Nein

**Comment by xwolfde** [comment]
freitextfelder ermöglichen das dann
