### ISSUE TITLE
Angaben zu mehr als einer Website werden nicht auf die Impressumsseite übernommen

### ISSUE THREAD

**Issue by m-w** [RRZE-Webteam/rrze-legal#73]
In den Einstellungen lassen sich unter "Impressum", Punkt "Webauftritte" weitere Domains eintragen: 

> Wenn dieses Impressum für mehr als eine Website gilt, fügen Sie hier die Domain-Namen der anderen Websites hinzu. Bitte geben Sie einen Domainnamen pro Zeile ein.

Die zusätzlichen Einträge werden jedoch nur bei der Erklärung zur Barrierefreiheit angezeigt und nicht beim Impressum.

**Comment by xwolfde** [comment]
Unter Haftungsauschluss
