### ISSUE TITLE
Titel der Endpoint-Seiten nicht korrekt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-legal#86]
Der wp_title() des Endpoints ist leider noch fehlerhaft.

Biespiel:
https://www.rrze.fau.de/datenschutz/
zeigt als Titel im Header:
"Die Liebe zum Detail macht den Unterschied"

**Comment by xwolfde** [comment]
Trifft auch bei den anderen Seiten zu (Impressum und Barrierefreiheit).

**Comment by rvdforst** [comment]
Fehler wurde behoben. Vgl. 6da736cb3aaefb663ec752d7573a13176db8f4a2
