### ISSUE TITLE
Config verschieben

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-legal#9]
Konfigurationswerte und änderbare Optionen aus includes/Options.php 
verschieben in ein Config-Bereich. Ggf. z.B. /config/ unter dem Hauptverzeichnis.

Ggf. auch anstelle eines PHP-Arrays die Nutzung von JSON in Betracht ziehen

**Comment by rvdforst** [comment]
Schließlich wurde eine PHP-Datei verwendet, die die Plugin-Einstellungen in einem einzigen Array (./settings/settings.php) speichert. Der Grund, keine JSON-Datei zu verwenden, ist, dass Elemente in den PHP-Einstellungen dynamische Werte enthalten können. Die PHP-Klasse, die die Einstellungsdateien liest, ist \RRZE\Legal\Settings
