### ISSUE TITLE
[enhancement] Allow adding other default domains

### ISSUE THREAD

**Issue by sebastian-schindler** [RRZE-Webteam/rrze-legal#98]
The privacy page displays some FAU-specific default text only in case of `is_default_domain`. However, this makes testing a new website difficult. For example, our ECAP test website lives under a different domain (web.test.ecap.work) than the live website (ecap.nat.fau.de).
It would be nice if this requirement would either not be hard-coded, or if there would be a form in the plugin settings to add a domain which will be treated as if it were the default domain.
Alternatively, if this is specifically not wanted (understandably), then add a warning text in the settings, that the domain of the website changes the displayed content?

**Comment by rvdforst** [comment]
Ich habe den Filter 'rrze_legal_fau_domains' hinzugefügt, damit die Default FAU-Domänen angepasst oder ersetzt werden können. Beispiel:
`
add_filter(
    'rrze_legal_fau_domains', 
    fn($domains) => [...$domains, 'ecap.work']
);
`
