### ISSUE TITLE
Schwere Rechtschreibfehler in englischen Texten

### ISSUE THREAD

**Issue by sebastian-schindler** [RRZE-Webteam/rrze-legal#99]
In den englischen Versionen der Barrierfreiheits-Pflichttexte bestehen eingie schwere Rechtschreibfehler, welche das Verständnis des Textes teilweise fast unmöglich machen. Übersetzungen der deutschen Versionen ins Englische mit Hilfe einschlägiger Tools (deepl.com etc.) liefern durchgehend bessere Ergebnisse.

1. 
> You may have shortcomings in meeting the requirements notify the accessibility or information that is not accessible be presented barrier-free.

besser:
> You can report deficiencies in compliance with accessibility requirements or request accessible information that does not need to be presented in an accessible manner.

2. 
> Remains a request for the possibility of contact within six weeks in full or in part unanswered, the competent authority checks at the request of the user, whether in the context of Monitoring against the operators of the web offer measures are required.

besser:
> If a request via the contact option remains wholly or partially unanswered within six weeks, the competent supervisory authority shall examine, at the request of the user, whether measures are necessary in the context of monitoring vis-à-vis the obligated party.

**Comment by rvdforst** [comment]
Ist erledigt. Vgl. https://github.com/RRZE-Webteam/rrze-legal/commit/16657884db00b3962f97fe058db7562318fc3851
